"""Obsidian vault sync — mirror agent conversations, knowledge, and briefings as markdown."""
import logging
from datetime import datetime, timezone
from pathlib import Path
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database.models import Conversation, KnowledgeBase
from app.database import models  # for type hints if needed

logger = logging.getLogger(__name__)


def _sanitize(name: str) -> str:
    """Strip characters unsafe for filenames; keep common punctuation."""
    return "".join(c if c.isalnum() or c in " _-.,;:!?" else "_" for c in name).strip() or "untitled"


async def sync_vault(db: AsyncSession, vault_path: str) -> dict:
    """Mirror all Socrates data into the vault under 'Socrates AI/'.

    Returns {written: n} count of files written.
    """
    vault = Path(vault_path)
    socrates = vault / "Socrates AI"
    socrates.mkdir(parents=True, exist_ok=True)

    written = 0

    # ── Conversations ──
    conv_dir = socrates / "Conversations"
    conv_dir.mkdir(exist_ok=True)
    result = await db.execute(
        select(Conversation).order_by(Conversation.last_message_at.desc().nullslast())
    )
    conversations = result.scalars().all()
    for conv in conversations:
        agent = conv.extra_metadata.get("agent_name", "unknown") if conv.extra_metadata else "unknown"
        when = conv.last_message_at or conv.created_at
        date_str = when.strftime("%Y-%m-%d") if when else "unknown-date"
        channel = conv.channel or "unknown"
        filename = _sanitize(f"{agent}-{date_str}-{channel}-{conv.id.hex[:8]}") + ".md"
        content = [
            f"# Conversation: {agent} ({date_str})",
            f"",
            f"- **Channel**: {channel}",
            f"- **Date**: {when.strftime('%Y-%m-%d %H:%M UTC') if when else 'unknown'}",
            f"- **Conversation ID**: `{conv.id}`",
            f"- **Status**: {conv.status}",
        ]
        if conv.lead_id:
            content.append(f"- **Lead ID**: `{conv.lead_id}`")
        if conv.client_id:
            content.append(f"- **Client ID**: `{conv.client_id}`")
        content.append("")
        (conv_dir / filename).write_text("\n".join(content), encoding="utf-8")
        written += 1

    # ── Knowledge ──
    know_dir = socrates / "Knowledge"
    know_dir.mkdir(exist_ok=True)
    result = await db.execute(select(KnowledgeBase).order_by(KnowledgeBase.created_at.desc()))
    articles = result.scalars().all()
    for art in articles:
        tags_str = ", ".join(art.tags) if art.tags else ""
        category_dir = know_dir / _sanitize(art.category or "Uncategorized")
        category_dir.mkdir(exist_ok=True)
        filename = _sanitize(art.title) + ".md"
        content = [
            f"# {art.title}",
            f"",
        ]
        if art.category:
            content.append(f"- **Category**: {art.category}")
        if tags_str:
            content.append(f"- **Tags**: {tags_str}")
        content.append(f"- **Created**: {art.created_at.strftime('%Y-%m-%d') if art.created_at else 'unknown'}")
        content.append(f"- **ID**: `{art.id}`")
        content.append("")
        content.append("---")
        content.append("")
        content.append(art.content)
        (category_dir / filename).write_text("\n".join(content), encoding="utf-8")
        written += 1

    # ── Briefings (daily summaries, generated each sync pass) ──
    brief_dir = socrates / "Briefings"
    brief_dir.mkdir(exist_ok=True)
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    brief_content = [
        f"# Socrates AI Briefing — {today}",
        f"",
        f"- **Active conversations**: {len(conversations) if conversations else 0}",
        f"- **Knowledge articles**: {len(articles) if articles else 0}",
        f"- **Last synced**: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        f"",
        f"---",
        f"*Auto-generated by Socrates AI sync at {datetime.now(timezone.utc).isoformat()}*",
    ]
    (brief_dir / f"briefing-{today}.md").write_text("\n".join(brief_content), encoding="utf-8")
    written += 1

    logger.info(f"Obsidian sync wrote {written} files to {vault_path}")
    return {"written": written}
